# Generated by Django 5.2.5 on 2025-08-20 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_category', models.CharField(max_length=50)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('stock_exposure', models.JSONField(default=dict)),
                ('mf_exposure', models.JSONField(default=dict)),
                ('fd_value', models.FloatField(default=0.0)),
                ('calculation_mode', models.CharField(choices=[('zerodha', 'Zerodha'), ('manual', 'Manual')], default='zerodha', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profile',
            },
        ),
        migrations.CreateModel(
            name='ZerodhaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=100)),
                ('zerodha_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('broker', models.CharField(blank=True, max_length=50, null=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('order_types', models.JSONField(blank=True, default=list)),
                ('exchanges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zerodha_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zerodha_user',
            },
        ),
    ]
