# Generated by Django 5.2.12 on 2026-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zerodhauser",
            name="access_token",
            field=models.TextField(db_column="access_token"),
        ),
        migrations.RenameField(
            model_name="zerodhauser",
            old_name="access_token",
            new_name="_access_token",
        ),
        migrations.RemoveField(
            model_name="zerodhauser",
            name="refresh_token",
        ),
        migrations.AddField(
            model_name="zerodhauser",
            name="_refresh_token",
            field=models.TextField(blank=True, db_column="refresh_token", null=True),
        ),
    ]
