# Generated by Django 5.2.5 on 2025-08-20 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentSalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearsOfService', models.IntegerField()),
                ('employerType', models.CharField(max_length=100)),
                ('pensionScheme', models.CharField(max_length=100)),
                ('pensionBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employerContribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('BMI', models.FloatField()),
                ('Physical_Activity', models.CharField(max_length=50)),
                ('Smoking_Status', models.CharField(max_length=20)),
                ('Alcohol_Consumption', models.CharField(max_length=20)),
                ('Diet', models.CharField(max_length=50)),
                ('Blood_Pressure', models.CharField(max_length=20)),
                ('Cholesterol', models.IntegerField()),
                ('Asthma', models.BooleanField(default=False)),
                ('Diabetes', models.BooleanField(default=False)),
                ('Heart_Disease', models.BooleanField(default=False)),
                ('Hypertension', models.BooleanField(default=False)),
                ('predicted_life_expectancy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life_expectancy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetirementInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plannedRetirementAge', models.IntegerField()),
                ('retirementLifestyle', models.CharField(max_length=50)),
                ('monthlyRetirementExpense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('legacyGoal', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('maritalStatus', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('numberOfDependants', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
