# Generated by Django 5.1.13 on 2026-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_incomestatus_yourcontribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomestatus",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
