# Generated by Django 5.1.13 on 2026-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_incomestatus_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="spouseName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
